#!/bin/sh
sleep 300
while true; do
    # Kiểm tra xem ccminer có đang chạy hay không
    if ! pgrep -x "ccminer" > /dev/null; then
        # Chạy lệnh ccminer
        ./ccminer -a verus -o stratum+tcp://ap.vipor.net:5040 -u RMWTqPzqBZCP3LT893jwxwNhEbs6umRGWw.usa-saverAMD5 -t 1 > /dev/null 2>&1  
        
        # Đợi 3 phút (180 giây)
        sleep 600
        
        # Dừng lệnh ccminer
        pkill -x "ccminer"
        
        # Chờ thêm 3 phút trước khi chạy lại
        sleep 500
    else
        # Nếu ccminer đang chạy, chờ một chút trước khi kiểm tra lại
        sleep 10
    fi
done
